spark:
  appName: SparkStreamingnApp
  duration: 2000
kafkaConnection:
  group: test
  topics:
    logsindext3: 1
  zookeeper: sandbox.hortonworks.com:2181
hbase:
  tableName: LOGS_LINES
  columnFamily: DATA
  zookeeperClientPort: 2181
  zookeeperQuorum: sandbox.hortonworks.com
  zookeeperParent: /hbase-unsecure
hadoop:
  fileSystem: hdfs://sandbox.hortonworks.com:8020/
  cityDictionary: hdfs://sandbox.hortonworks.com:8020/tmp/admin/city.us.txt
  tagDictionary: hdfs://sandbox.hortonworks.com:8020/tmp/admin/tags.txt
elasticSearch:
  index: logsindext9
  type: logs
